PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://rs.tdwg.org/dwc/terms/>


SELECT DISTINCT ?x WHERE {
{{{uri}} rdfs:label ?x.}
UNION { {{uri}} dc:scientificName ?x.}
UNION { {{uri}} skos:prefLabel ?x.}
}
